### ISSUE TITLE
ROS2

### ISSUE THREAD

**Issue by samuk** [Andrew-rw/vl53l0x_driver#2]
Are you thinking about doing a ROS2 version?

**Comment by Andrew-rw** [comment]
Hi. Soon I'm going to migrate all my projects to ROS2, so this driver will be migrated also. But currently it is hard to say when it happens.

And if you have already started doing that, I'd be happy to accept pull requests:)

**Comment by samuk** [comment]
Ah I found this: https://github.com/slaghuis/ROS2-VL53L1X I'll give that a go
